server {
    listen 80;
    server_name okagami-mochi.net; # 自分のドメイン名を指定する localhostなど
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name okagami-mochi.net; # 自分のドメイン名を指定する

    #フォルダに各自の証明書をおいてください
    ssl_certificate /etc/nginx/ssl/fullchain.pem; 
    ssl_certificate_key /etc/nginx/ssl/privkey.pem; 
    root /var/www/html/public;

    client_max_body_size 50M;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
    add_header X-XSS-Protection "1; mode=block";

    index index.php index.html;

    charset utf-8;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml+rss text/javascript; 

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_hide_header X-Powered-By;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|mp3|wav)$ {
        expires 1M;
        access_log off;
        add_header Cache-Control "public";
    }
    
    location = /favicon.ico { 
        access_log off;
        log_not_found off;
      }
    location = /robots.txt  { 
        access_log off; 
        log_not_found off;
    }

    error_page 404 /index.php;

    location ~ /\.(?!well-known).* {
        deny all;
    }
}